apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-adr
  description: Journal entry for the life of the Notify software
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
